# Generated by Django 5.2.4 on 2026-01-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='numero_orden',
            field=models.CharField(max_length=20),
        ),
    ]
