# Generated by Django 5.2.4 on 2026-01-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_historial_descripcion_alter_historial_numero_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='pendiente',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
