# Generated by Django 5.2.4 on 2026-01-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_historial_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_admin',
            name='solo_consulta',
            field=models.BooleanField(default=False, help_text='Si está activo, el usuario solo puede consultar y descargar el historial, no registrar ingresos.'),
        ),
    ]
