# Generated by Django 5.2.4 on 2026-02-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_user_admin_solo_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('cedula', models.CharField(max_length=50)),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Acceso Persona',
                'verbose_name_plural': 'Accesos Personas',
            },
        ),
    ]
