# Generated by Django. Add migration for motivo_ingreso in AccesoPersona
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('app2', '0006_accesopersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesopersona',
            name='motivo_ingreso',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
    ]
