# Generated by Django. Add migration for hora_salida in AccesoPersona
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('app2', '0007_accesopersona_motivo_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesopersona',
            name='hora_salida',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
