# Generated by Django 5.2.4 on 2026-02-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_accesopersona_hora_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesopersona',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
