# Generated by Django 5.2.4 on 2026-02-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_accesopersona_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_admin',
            name='permiso_auditoria',
            field=models.CharField(choices=[('none', 'Sin acceso'), ('consulta', 'Solo consulta'), ('total', 'Total')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='permiso_control',
            field=models.CharField(choices=[('none', 'Sin acceso'), ('consulta', 'Solo consulta'), ('total', 'Total')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='permiso_control_personas',
            field=models.CharField(choices=[('none', 'Sin acceso'), ('consulta', 'Solo consulta'), ('total', 'Total')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='permiso_reportes',
            field=models.CharField(choices=[('none', 'Sin acceso'), ('consulta', 'Solo consulta'), ('total', 'Total')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='permiso_usuarios',
            field=models.CharField(choices=[('none', 'Sin acceso'), ('consulta', 'Solo consulta'), ('total', 'Total')], default='none', max_length=10),
        ),
    ]
