# Generated by Django 5.2.4 on 2026-02-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_user_admin_permiso_auditoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_admin',
            name='permiso_auditoria',
            field=models.BooleanField(default=False, help_text='Acceso a Auditoría'),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='permiso_control',
            field=models.BooleanField(default=False, help_text='Acceso a Control de entradas'),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='permiso_control_personas',
            field=models.BooleanField(default=False, help_text='Acceso a Control de personas'),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='permiso_reportes',
            field=models.BooleanField(default=False, help_text='Acceso a Reportes'),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='permiso_usuarios',
            field=models.BooleanField(default=False, help_text='Acceso a Usuarios'),
        ),
    ]
