# Generated by Django 5.2.4 on 2026-03-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_alter_user_admin_permiso_auditoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesopersona',
            name='autorizado_por',
            field=models.CharField(blank=True, help_text='Nombre de quien autorizó el ingreso', max_length=100, null=True),
        ),
    ]
