# Generated by Django 5.2.4 on 2026-03-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_accesopersona_autorizado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesopersona',
            name='a_quien_visita',
            field=models.CharField(blank=True, help_text='Persona a quien visita', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accesopersona',
            name='estado_visita',
            field=models.CharField(choices=[('aprobada', 'Aprobada'), ('negada', 'Negada')], default='aprobada', help_text='Estado de la visita: aprobada o negada', max_length=10),
        ),
    ]
