# Generated by Django 5.2.4 on 2026-03-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_accesopersona_a_quien_visita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesopersona',
            name='tiempo_visita',
            field=models.PositiveIntegerField(blank=True, help_text='Duración de la visita en minutos', null=True),
        ),
    ]
