# Generated by Django 5.2.4 on 2025-10-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_num', models.CharField(blank=True, max_length=50, null=True)),
                ('fec_emis', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('co_cli', models.CharField(blank=True, max_length=50, null=True)),
                ('prov_des', models.CharField(blank=True, max_length=200, null=True)),
                ('descrip', models.TextField(blank=True, null=True)),
                ('hcoment', models.TextField(blank=True, null=True)),
                ('rcoment', models.TextField(blank=True, null=True)),
                ('reng_num', models.IntegerField(blank=True, null=True)),
                ('co_art', models.CharField(blank=True, max_length=50, null=True)),
                ('art_des', models.CharField(blank=True, max_length=200, null=True)),
                ('lin_des', models.CharField(blank=True, max_length=200, null=True)),
                ('total_art', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('uni_venta', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pendiente', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'reng_ord',
                'managed': False,
            },
        ),
    ]
